apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-promtail
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.*
    helm:
      releaseName: loki-stack
      values: |
        grafana:
          enabled: false
        prometheus:
          enabled: false
        promtail:
          enabled: true
          serviceMonitor:
            enabled: true
        loki:
          enabled: true
          persistence:
            enabled: false
